# coding: utf-8

"""
    DocuSign Monitor API - v2

    An API for an integrator to access the features of DocuSign Monitor  # noqa: E501

    OpenAPI spec version: v2.0
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Aggregation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aggregation_name': 'str'
    }

    attribute_map = {
        'aggregation_name': 'aggregationName'
    }

    def __init__(self, aggregation_name=None):  # noqa: E501
        """Aggregation - a model defined in Swagger"""  # noqa: E501

        self._aggregation_name = None
        self.discriminator = None

        if aggregation_name is not None:
            self.aggregation_name = aggregation_name

    @property
    def aggregation_name(self):
        """Gets the aggregation_name of this Aggregation.  # noqa: E501


        :return: The aggregation_name of this Aggregation.  # noqa: E501
        :rtype: str
        """
        return self._aggregation_name

    @aggregation_name.setter
    def aggregation_name(self, aggregation_name):
        """Sets the aggregation_name of this Aggregation.


        :param aggregation_name: The aggregation_name of this Aggregation.  # noqa: E501
        :type: str
        """

        self._aggregation_name = aggregation_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Aggregation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Aggregation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
