# coding: utf-8

"""
    Monitor API

    An API for an integrator to access the features of Docusign Monitor  # noqa: E501

    OpenAPI spec version: v3.0
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_monitor.client.configuration import Configuration


class Browser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'family': 'str',
        'version': 'Version'
    }

    attribute_map = {
        'family': 'family',
        'version': 'version'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """Browser - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._family = None
        self._version = None
        self.discriminator = None

        setattr(self, "_{}".format('family'), kwargs.get('family', None))
        setattr(self, "_{}".format('version'), kwargs.get('version', None))

    @property
    def family(self):
        """Gets the family of this Browser.  # noqa: E501


        :return: The family of this Browser.  # noqa: E501
        :rtype: str
        """
        return self._family

    @family.setter
    def family(self, family):
        """Sets the family of this Browser.


        :param family: The family of this Browser.  # noqa: E501
        :type: str
        """

        self._family = family

    @property
    def version(self):
        """Gets the version of this Browser.  # noqa: E501


        :return: The version of this Browser.  # noqa: E501
        :rtype: Version
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Browser.


        :param version: The version of this Browser.  # noqa: E501
        :type: Version
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Browser, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Browser):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Browser):
            return True

        return self.to_dict() != other.to_dict()
