# coding: utf-8

"""
    Monitor API

    An API for an integrator to access the features of Docusign Monitor  # noqa: E501

    OpenAPI spec version: v3.0
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_monitor.client.configuration import Configuration


class IpAddressLocation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'latitude': 'float',
        'longitude': 'float',
        'country': 'str',
        'state': 'str',
        'city': 'str'
    }

    attribute_map = {
        'latitude': 'latitude',
        'longitude': 'longitude',
        'country': 'country',
        'state': 'state',
        'city': 'city'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """IpAddressLocation - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._latitude = None
        self._longitude = None
        self._country = None
        self._state = None
        self._city = None
        self.discriminator = None

        setattr(self, "_{}".format('latitude'), kwargs.get('latitude', None))
        setattr(self, "_{}".format('longitude'), kwargs.get('longitude', None))
        setattr(self, "_{}".format('country'), kwargs.get('country', None))
        setattr(self, "_{}".format('state'), kwargs.get('state', None))
        setattr(self, "_{}".format('city'), kwargs.get('city', None))

    @property
    def latitude(self):
        """Gets the latitude of this IpAddressLocation.  # noqa: E501


        :return: The latitude of this IpAddressLocation.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this IpAddressLocation.


        :param latitude: The latitude of this IpAddressLocation.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this IpAddressLocation.  # noqa: E501


        :return: The longitude of this IpAddressLocation.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this IpAddressLocation.


        :param longitude: The longitude of this IpAddressLocation.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def country(self):
        """Gets the country of this IpAddressLocation.  # noqa: E501


        :return: The country of this IpAddressLocation.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this IpAddressLocation.


        :param country: The country of this IpAddressLocation.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def state(self):
        """Gets the state of this IpAddressLocation.  # noqa: E501


        :return: The state of this IpAddressLocation.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this IpAddressLocation.


        :param state: The state of this IpAddressLocation.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def city(self):
        """Gets the city of this IpAddressLocation.  # noqa: E501


        :return: The city of this IpAddressLocation.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this IpAddressLocation.


        :param city: The city of this IpAddressLocation.  # noqa: E501
        :type: str
        """

        self._city = city

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IpAddressLocation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IpAddressLocation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IpAddressLocation):
            return True

        return self.to_dict() != other.to_dict()
