# coding: utf-8

"""
    Monitor API

    An API for an integrator to access the features of Docusign Monitor  # noqa: E501

    OpenAPI spec version: v3.0
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_monitor.client.configuration import Configuration


class StreamingEventRow(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'timestamp': 'datetime',
        'event_id': 'str',
        'site': 'str',
        'account_id': 'str',
        'organization_id': 'str',
        'user_id': 'str',
        'integrator_key': 'str',
        'user_agent': 'str',
        'user_agent_client_info': 'UserAgentClientInfo',
        'ip_address': 'str',
        'ip_address_location': 'IpAddressLocation',
        'object': 'str',
        'action': 'str',
        '_property': 'str',
        'field': 'str',
        'result': 'str',
        'source': 'str',
        'is_user_member_of_domain': 'bool',
        'referenced_user_is_member_of_domain': 'bool',
        'referenced_user_id': 'str',
        'proxy_status': 'str',
        'proxy_type': 'str',
        'proxy_level': 'str',
        'latitude': 'float',
        'longitude': 'float',
        'city': 'str',
        'state': 'str',
        'country': 'str',
        'device': 'str',
        'browser': 'str',
        'os': 'str',
        'affected_user_id': 'str',
        'affected_user_is_member_of_domain': 'bool',
        'data': 'dict(str, object)'
    }

    attribute_map = {
        'timestamp': 'timestamp',
        'event_id': 'eventId',
        'site': 'site',
        'account_id': 'accountId',
        'organization_id': 'organizationId',
        'user_id': 'userId',
        'integrator_key': 'integratorKey',
        'user_agent': 'userAgent',
        'user_agent_client_info': 'userAgentClientInfo',
        'ip_address': 'ipAddress',
        'ip_address_location': 'ipAddressLocation',
        'object': 'object',
        'action': 'action',
        '_property': 'property',
        'field': 'field',
        'result': 'result',
        'source': 'source',
        'is_user_member_of_domain': 'isUserMemberOfDomain',
        'referenced_user_is_member_of_domain': 'referencedUserIsMemberOfDomain',
        'referenced_user_id': 'referencedUserId',
        'proxy_status': 'proxyStatus',
        'proxy_type': 'proxyType',
        'proxy_level': 'proxyLevel',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'city': 'city',
        'state': 'state',
        'country': 'country',
        'device': 'device',
        'browser': 'browser',
        'os': 'os',
        'affected_user_id': 'affectedUserId',
        'affected_user_is_member_of_domain': 'affectedUserIsMemberOfDomain',
        'data': 'data'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """StreamingEventRow - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._timestamp = None
        self._event_id = None
        self._site = None
        self._account_id = None
        self._organization_id = None
        self._user_id = None
        self._integrator_key = None
        self._user_agent = None
        self._user_agent_client_info = None
        self._ip_address = None
        self._ip_address_location = None
        self._object = None
        self._action = None
        self.__property = None
        self._field = None
        self._result = None
        self._source = None
        self._is_user_member_of_domain = None
        self._referenced_user_is_member_of_domain = None
        self._referenced_user_id = None
        self._proxy_status = None
        self._proxy_type = None
        self._proxy_level = None
        self._latitude = None
        self._longitude = None
        self._city = None
        self._state = None
        self._country = None
        self._device = None
        self._browser = None
        self._os = None
        self._affected_user_id = None
        self._affected_user_is_member_of_domain = None
        self._data = None
        self.discriminator = None

        setattr(self, "_{}".format('timestamp'), kwargs.get('timestamp', None))
        setattr(self, "_{}".format('event_id'), kwargs.get('event_id', None))
        setattr(self, "_{}".format('site'), kwargs.get('site', None))
        setattr(self, "_{}".format('account_id'), kwargs.get('account_id', None))
        setattr(self, "_{}".format('organization_id'), kwargs.get('organization_id', None))
        setattr(self, "_{}".format('user_id'), kwargs.get('user_id', None))
        setattr(self, "_{}".format('integrator_key'), kwargs.get('integrator_key', None))
        setattr(self, "_{}".format('user_agent'), kwargs.get('user_agent', None))
        setattr(self, "_{}".format('user_agent_client_info'), kwargs.get('user_agent_client_info', None))
        setattr(self, "_{}".format('ip_address'), kwargs.get('ip_address', None))
        setattr(self, "_{}".format('ip_address_location'), kwargs.get('ip_address_location', None))
        setattr(self, "_{}".format('object'), kwargs.get('object', None))
        setattr(self, "_{}".format('action'), kwargs.get('action', None))
        setattr(self, "_{}".format('_property'), kwargs.get('_property', None))
        setattr(self, "_{}".format('field'), kwargs.get('field', None))
        setattr(self, "_{}".format('result'), kwargs.get('result', None))
        setattr(self, "_{}".format('source'), kwargs.get('source', None))
        setattr(self, "_{}".format('is_user_member_of_domain'), kwargs.get('is_user_member_of_domain', None))
        setattr(self, "_{}".format('referenced_user_is_member_of_domain'), kwargs.get('referenced_user_is_member_of_domain', None))
        setattr(self, "_{}".format('referenced_user_id'), kwargs.get('referenced_user_id', None))
        setattr(self, "_{}".format('proxy_status'), kwargs.get('proxy_status', None))
        setattr(self, "_{}".format('proxy_type'), kwargs.get('proxy_type', None))
        setattr(self, "_{}".format('proxy_level'), kwargs.get('proxy_level', None))
        setattr(self, "_{}".format('latitude'), kwargs.get('latitude', None))
        setattr(self, "_{}".format('longitude'), kwargs.get('longitude', None))
        setattr(self, "_{}".format('city'), kwargs.get('city', None))
        setattr(self, "_{}".format('state'), kwargs.get('state', None))
        setattr(self, "_{}".format('country'), kwargs.get('country', None))
        setattr(self, "_{}".format('device'), kwargs.get('device', None))
        setattr(self, "_{}".format('browser'), kwargs.get('browser', None))
        setattr(self, "_{}".format('os'), kwargs.get('os', None))
        setattr(self, "_{}".format('affected_user_id'), kwargs.get('affected_user_id', None))
        setattr(self, "_{}".format('affected_user_is_member_of_domain'), kwargs.get('affected_user_is_member_of_domain', None))
        setattr(self, "_{}".format('data'), kwargs.get('data', None))

    @property
    def timestamp(self):
        """Gets the timestamp of this StreamingEventRow.  # noqa: E501


        :return: The timestamp of this StreamingEventRow.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this StreamingEventRow.


        :param timestamp: The timestamp of this StreamingEventRow.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    @property
    def event_id(self):
        """Gets the event_id of this StreamingEventRow.  # noqa: E501


        :return: The event_id of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._event_id

    @event_id.setter
    def event_id(self, event_id):
        """Sets the event_id of this StreamingEventRow.


        :param event_id: The event_id of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._event_id = event_id

    @property
    def site(self):
        """Gets the site of this StreamingEventRow.  # noqa: E501


        :return: The site of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._site

    @site.setter
    def site(self, site):
        """Sets the site of this StreamingEventRow.


        :param site: The site of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._site = site

    @property
    def account_id(self):
        """Gets the account_id of this StreamingEventRow.  # noqa: E501


        :return: The account_id of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this StreamingEventRow.


        :param account_id: The account_id of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._account_id = account_id

    @property
    def organization_id(self):
        """Gets the organization_id of this StreamingEventRow.  # noqa: E501


        :return: The organization_id of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this StreamingEventRow.


        :param organization_id: The organization_id of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def user_id(self):
        """Gets the user_id of this StreamingEventRow.  # noqa: E501


        :return: The user_id of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this StreamingEventRow.


        :param user_id: The user_id of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def integrator_key(self):
        """Gets the integrator_key of this StreamingEventRow.  # noqa: E501


        :return: The integrator_key of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._integrator_key

    @integrator_key.setter
    def integrator_key(self, integrator_key):
        """Sets the integrator_key of this StreamingEventRow.


        :param integrator_key: The integrator_key of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._integrator_key = integrator_key

    @property
    def user_agent(self):
        """Gets the user_agent of this StreamingEventRow.  # noqa: E501


        :return: The user_agent of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._user_agent

    @user_agent.setter
    def user_agent(self, user_agent):
        """Sets the user_agent of this StreamingEventRow.


        :param user_agent: The user_agent of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._user_agent = user_agent

    @property
    def user_agent_client_info(self):
        """Gets the user_agent_client_info of this StreamingEventRow.  # noqa: E501


        :return: The user_agent_client_info of this StreamingEventRow.  # noqa: E501
        :rtype: UserAgentClientInfo
        """
        return self._user_agent_client_info

    @user_agent_client_info.setter
    def user_agent_client_info(self, user_agent_client_info):
        """Sets the user_agent_client_info of this StreamingEventRow.


        :param user_agent_client_info: The user_agent_client_info of this StreamingEventRow.  # noqa: E501
        :type: UserAgentClientInfo
        """

        self._user_agent_client_info = user_agent_client_info

    @property
    def ip_address(self):
        """Gets the ip_address of this StreamingEventRow.  # noqa: E501


        :return: The ip_address of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._ip_address

    @ip_address.setter
    def ip_address(self, ip_address):
        """Sets the ip_address of this StreamingEventRow.


        :param ip_address: The ip_address of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._ip_address = ip_address

    @property
    def ip_address_location(self):
        """Gets the ip_address_location of this StreamingEventRow.  # noqa: E501


        :return: The ip_address_location of this StreamingEventRow.  # noqa: E501
        :rtype: IpAddressLocation
        """
        return self._ip_address_location

    @ip_address_location.setter
    def ip_address_location(self, ip_address_location):
        """Sets the ip_address_location of this StreamingEventRow.


        :param ip_address_location: The ip_address_location of this StreamingEventRow.  # noqa: E501
        :type: IpAddressLocation
        """

        self._ip_address_location = ip_address_location

    @property
    def object(self):
        """Gets the object of this StreamingEventRow.  # noqa: E501


        :return: The object of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object):
        """Sets the object of this StreamingEventRow.


        :param object: The object of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._object = object

    @property
    def action(self):
        """Gets the action of this StreamingEventRow.  # noqa: E501


        :return: The action of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this StreamingEventRow.


        :param action: The action of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._action = action

    @property
    def _property(self):
        """Gets the _property of this StreamingEventRow.  # noqa: E501


        :return: The _property of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self.__property

    @_property.setter
    def _property(self, _property):
        """Sets the _property of this StreamingEventRow.


        :param _property: The _property of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self.__property = _property

    @property
    def field(self):
        """Gets the field of this StreamingEventRow.  # noqa: E501


        :return: The field of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this StreamingEventRow.


        :param field: The field of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._field = field

    @property
    def result(self):
        """Gets the result of this StreamingEventRow.  # noqa: E501


        :return: The result of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this StreamingEventRow.


        :param result: The result of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._result = result

    @property
    def source(self):
        """Gets the source of this StreamingEventRow.  # noqa: E501


        :return: The source of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this StreamingEventRow.


        :param source: The source of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def is_user_member_of_domain(self):
        """Gets the is_user_member_of_domain of this StreamingEventRow.  # noqa: E501


        :return: The is_user_member_of_domain of this StreamingEventRow.  # noqa: E501
        :rtype: bool
        """
        return self._is_user_member_of_domain

    @is_user_member_of_domain.setter
    def is_user_member_of_domain(self, is_user_member_of_domain):
        """Sets the is_user_member_of_domain of this StreamingEventRow.


        :param is_user_member_of_domain: The is_user_member_of_domain of this StreamingEventRow.  # noqa: E501
        :type: bool
        """

        self._is_user_member_of_domain = is_user_member_of_domain

    @property
    def referenced_user_is_member_of_domain(self):
        """Gets the referenced_user_is_member_of_domain of this StreamingEventRow.  # noqa: E501


        :return: The referenced_user_is_member_of_domain of this StreamingEventRow.  # noqa: E501
        :rtype: bool
        """
        return self._referenced_user_is_member_of_domain

    @referenced_user_is_member_of_domain.setter
    def referenced_user_is_member_of_domain(self, referenced_user_is_member_of_domain):
        """Sets the referenced_user_is_member_of_domain of this StreamingEventRow.


        :param referenced_user_is_member_of_domain: The referenced_user_is_member_of_domain of this StreamingEventRow.  # noqa: E501
        :type: bool
        """

        self._referenced_user_is_member_of_domain = referenced_user_is_member_of_domain

    @property
    def referenced_user_id(self):
        """Gets the referenced_user_id of this StreamingEventRow.  # noqa: E501


        :return: The referenced_user_id of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._referenced_user_id

    @referenced_user_id.setter
    def referenced_user_id(self, referenced_user_id):
        """Sets the referenced_user_id of this StreamingEventRow.


        :param referenced_user_id: The referenced_user_id of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._referenced_user_id = referenced_user_id

    @property
    def proxy_status(self):
        """Gets the proxy_status of this StreamingEventRow.  # noqa: E501


        :return: The proxy_status of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._proxy_status

    @proxy_status.setter
    def proxy_status(self, proxy_status):
        """Sets the proxy_status of this StreamingEventRow.


        :param proxy_status: The proxy_status of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._proxy_status = proxy_status

    @property
    def proxy_type(self):
        """Gets the proxy_type of this StreamingEventRow.  # noqa: E501


        :return: The proxy_type of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._proxy_type

    @proxy_type.setter
    def proxy_type(self, proxy_type):
        """Sets the proxy_type of this StreamingEventRow.


        :param proxy_type: The proxy_type of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._proxy_type = proxy_type

    @property
    def proxy_level(self):
        """Gets the proxy_level of this StreamingEventRow.  # noqa: E501


        :return: The proxy_level of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._proxy_level

    @proxy_level.setter
    def proxy_level(self, proxy_level):
        """Sets the proxy_level of this StreamingEventRow.


        :param proxy_level: The proxy_level of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._proxy_level = proxy_level

    @property
    def latitude(self):
        """Gets the latitude of this StreamingEventRow.  # noqa: E501


        :return: The latitude of this StreamingEventRow.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this StreamingEventRow.


        :param latitude: The latitude of this StreamingEventRow.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this StreamingEventRow.  # noqa: E501


        :return: The longitude of this StreamingEventRow.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this StreamingEventRow.


        :param longitude: The longitude of this StreamingEventRow.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def city(self):
        """Gets the city of this StreamingEventRow.  # noqa: E501


        :return: The city of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this StreamingEventRow.


        :param city: The city of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def state(self):
        """Gets the state of this StreamingEventRow.  # noqa: E501


        :return: The state of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this StreamingEventRow.


        :param state: The state of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def country(self):
        """Gets the country of this StreamingEventRow.  # noqa: E501


        :return: The country of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this StreamingEventRow.


        :param country: The country of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def device(self):
        """Gets the device of this StreamingEventRow.  # noqa: E501


        :return: The device of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._device

    @device.setter
    def device(self, device):
        """Sets the device of this StreamingEventRow.


        :param device: The device of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._device = device

    @property
    def browser(self):
        """Gets the browser of this StreamingEventRow.  # noqa: E501


        :return: The browser of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._browser

    @browser.setter
    def browser(self, browser):
        """Sets the browser of this StreamingEventRow.


        :param browser: The browser of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._browser = browser

    @property
    def os(self):
        """Gets the os of this StreamingEventRow.  # noqa: E501


        :return: The os of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._os

    @os.setter
    def os(self, os):
        """Sets the os of this StreamingEventRow.


        :param os: The os of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._os = os

    @property
    def affected_user_id(self):
        """Gets the affected_user_id of this StreamingEventRow.  # noqa: E501


        :return: The affected_user_id of this StreamingEventRow.  # noqa: E501
        :rtype: str
        """
        return self._affected_user_id

    @affected_user_id.setter
    def affected_user_id(self, affected_user_id):
        """Sets the affected_user_id of this StreamingEventRow.


        :param affected_user_id: The affected_user_id of this StreamingEventRow.  # noqa: E501
        :type: str
        """

        self._affected_user_id = affected_user_id

    @property
    def affected_user_is_member_of_domain(self):
        """Gets the affected_user_is_member_of_domain of this StreamingEventRow.  # noqa: E501


        :return: The affected_user_is_member_of_domain of this StreamingEventRow.  # noqa: E501
        :rtype: bool
        """
        return self._affected_user_is_member_of_domain

    @affected_user_is_member_of_domain.setter
    def affected_user_is_member_of_domain(self, affected_user_is_member_of_domain):
        """Sets the affected_user_is_member_of_domain of this StreamingEventRow.


        :param affected_user_is_member_of_domain: The affected_user_is_member_of_domain of this StreamingEventRow.  # noqa: E501
        :type: bool
        """

        self._affected_user_is_member_of_domain = affected_user_is_member_of_domain

    @property
    def data(self):
        """Gets the data of this StreamingEventRow.  # noqa: E501


        :return: The data of this StreamingEventRow.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this StreamingEventRow.


        :param data: The data of this StreamingEventRow.  # noqa: E501
        :type: dict(str, object)
        """

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StreamingEventRow, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StreamingEventRow):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StreamingEventRow):
            return True

        return self.to_dict() != other.to_dict()
