# coding: utf-8

"""
    Monitor API

    An API for an integrator to access the features of Docusign Monitor  # noqa: E501

    OpenAPI spec version: v3.0
    Contact: devcenter@docusign.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from docusign_monitor.client.configuration import Configuration


class UserAgentClientInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'browser': 'Browser',
        'device': 'Device',
        'os': 'Os'
    }

    attribute_map = {
        'browser': 'browser',
        'device': 'device',
        'os': 'os'
    }

    def __init__(self, _configuration=None, **kwargs):  # noqa: E501
        """UserAgentClientInfo - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._browser = None
        self._device = None
        self._os = None
        self.discriminator = None

        setattr(self, "_{}".format('browser'), kwargs.get('browser', None))
        setattr(self, "_{}".format('device'), kwargs.get('device', None))
        setattr(self, "_{}".format('os'), kwargs.get('os', None))

    @property
    def browser(self):
        """Gets the browser of this UserAgentClientInfo.  # noqa: E501


        :return: The browser of this UserAgentClientInfo.  # noqa: E501
        :rtype: Browser
        """
        return self._browser

    @browser.setter
    def browser(self, browser):
        """Sets the browser of this UserAgentClientInfo.


        :param browser: The browser of this UserAgentClientInfo.  # noqa: E501
        :type: Browser
        """

        self._browser = browser

    @property
    def device(self):
        """Gets the device of this UserAgentClientInfo.  # noqa: E501


        :return: The device of this UserAgentClientInfo.  # noqa: E501
        :rtype: Device
        """
        return self._device

    @device.setter
    def device(self, device):
        """Sets the device of this UserAgentClientInfo.


        :param device: The device of this UserAgentClientInfo.  # noqa: E501
        :type: Device
        """

        self._device = device

    @property
    def os(self):
        """Gets the os of this UserAgentClientInfo.  # noqa: E501


        :return: The os of this UserAgentClientInfo.  # noqa: E501
        :rtype: Os
        """
        return self._os

    @os.setter
    def os(self, os):
        """Sets the os of this UserAgentClientInfo.


        :param os: The os of this UserAgentClientInfo.  # noqa: E501
        :type: Os
        """

        self._os = os

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserAgentClientInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserAgentClientInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserAgentClientInfo):
            return True

        return self.to_dict() != other.to_dict()
